# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeepLearningSystem.ui'
#
# Created by: malianwei
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.core import QgsApplication
from qgis.PyQt.QtCore import Qt,QTranslator
import datetime,json
from cryptography.fernet import Fernet
from dialog.mainWin import mainWin
from os.path import dirname,join
from os import environ
base_dir = dirname(__file__)      
environ['PROJ_LIB'] = base_dir+'/settings'
key_path = join(base_dir, 'license', 'secret.key')
lic_path = join(base_dir, 'license', 'license.lic')
zh_Hans = join(base_dir, 'settings', 'zh-Hans.qm')
model_cofing_path = join(base_dir, 'settings', 'ModelsConfig.xml')
sample_cofing_path = join(base_dir, 'settings', 'SamplesConfig.xml')
train_set = join(base_dir, 'temp/sample', 'train_set.txt')
val_set = join(base_dir, 'temp/sample', 'val_set.txt')


if __name__ == "__main__":

    # 授权   
    # 从文件加载密钥
    with open(key_path, 'rb') as key_file:
        key = key_file.read()           
    # 创建Fernet对象
    fernet = Fernet(key)    
    with open(lic_path, "rb") as f:
        encrypted_license = f.read()         
    license_json = fernet.decrypt(encrypted_license).decode()
    license_data = json.loads(license_json)
    software_version = license_data.get("software_version")
    user_id = license_data.get("user_id")
    expiration_date = license_data.get("expiration_date")

    QgsApplication.setPrefixPath('', True)
    QgsApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    app = QgsApplication([], False)

    t = QTranslator()
    t.load(zh_Hans) 
    app.installTranslator(t)

    app.initQgis()

    myWindow = mainWin()
    
    # 在这里进行详细的验证，如检查版本、用户身份、期限和功能等
    if datetime.datetime.strptime(expiration_date, "%Y-%m-%d") < datetime.datetime.now():        
        from tools.CommonTool import show_info_message
        show_info_message(myWindow, '警告', f"许可截至：{expiration_date}！\n已过期，请联系技术人员！")
        myWindow.close()      
    else:   
        print('run')
        myWindow.show()
        # 关键：激活窗口并获取焦点
        myWindow.activateWindow()
        #myWindow.raise_()
        app.exec_()
        app.exitQgis()
