# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeepLearningSystem.ui'
#
# Created by: malianwei
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.core import QgsApplication
from qgis.PyQt.QtCore import Qt,QTranslator
from qgis.PyQt.QtWidgets import QMessageBox
import datetime,json
from cryptography.fernet import Fernet
from mainWin import mainWindow
        

if __name__ == "__main__":

    # 授权
    # 从文件加载密钥
    with open('./license/secret.key', 'rb') as key_file:
        key = key_file.read()           
    # 创建Fernet对象
    fernet = Fernet(key)

    with open('./license/license.lic', "rb") as f:
        encrypted_license = f.read()         
    license_json = fernet.decrypt(encrypted_license).decode()
    license_data = json.loads(license_json)
    software_version = license_data.get("software_version")
    user_id = license_data.get("user_id")
    expiration_date = license_data.get("expiration_date")

    QgsApplication.setPrefixPath(r'D:\AI_Test', True)
    QgsApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    app = QgsApplication([], False)

    t = QTranslator()
    t.load(r'.\settings\zh-Hans.qm')
    app.installTranslator(t)

    app.initQgis()

    myWindow = mainWindow()
    
    # 在这里进行详细的验证，如检查版本、用户身份、期限和功能等
    if datetime.datetime.strptime(expiration_date, "%Y-%m-%d") < datetime.datetime.now():        
        QMessageBox.question(myWindow, '警告', f"许可截至：{expiration_date}！\n已过期，请联系技术人员！", QMessageBox.Yes | QMessageBox.No,
                                        QMessageBox.No)
        myWindow.close()      
    else:   
        print('run')
        myWindow.show()
        app.exec_()
        app.exitQgis()
