# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeepLearningSystem.ui'
#
# Created by: malianwei
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.core import QgsProject, QgsLayerTreeModel, QgsRasterLayer, QgsVectorLayer, QgsMapLayer, QgsCoordinateReferenceSystem, QgsMapLayerType, QgsMapSettings
from qgis.gui import QgsMapCanvas, QgsLayerTreeView, QgsLayerTreeMapCanvasBridge, QgsMapToolPan, QgsMapToolZoom, QgsMapToolIdentifyFeature
from qgis.PyQt.QtWidgets import QAction, QMainWindow, QToolBar, QLabel, QHBoxLayout, QWidget, QFileDialog, QMessageBox, QDialog
from qgis.PyQt.QtGui import QIcon, QPixmap
from qgis.PyQt.QtCore import Qt, QMimeData
from qgis.PyQt.QtGui import QStandardItemModel, QStandardItem
from qgis.PyQt import QtWidgets,QtCore
from os.path import basename,join


class mainWindow(QMainWindow):

    def __init__(self):
        # 主窗口
        QMainWindow.__init__(self)
        self.resize(1200, 800)
        self.setWindowTitle("基于深度学习的遥感影像提取系统")  
        self.showMaximized()#最大化窗口       

        # 画布
        self.canvas = QgsMapCanvas()
        self.canvas.setCanvasColor(Qt.white)
        self.canvas.setVisible(True)
        self.canvas.xyCoordinates.connect(self.showXY)
        self.setAcceptDrops(True)# 允许拖拽文件   
        self.canvas.setDestinationCrs(QgsCoordinateReferenceSystem("EPSG:4326"))# 提前给予基本CRS
        self.firstAddLayer = True

        # 图层管理器(左)
        self.root = QgsProject.instance().layerTreeRoot()
        self.model = QgsLayerTreeModel(self.root,self)
        self.model.setFlag(QgsLayerTreeModel.AllowNodeReorder)
        self.model.setFlag(QgsLayerTreeModel.AllowNodeChangeVisibility)
        self.tocView = QgsLayerTreeView()
        self.tocView.setModel(self.model)
        self.tocView.setFixedWidth(300)
        self.bridge = QgsLayerTreeMapCanvasBridge(self.root, self.canvas,self)
        # 图层管理器中添加右键菜单
        from menu.ContextMenu import CustomMenuProvider
        self.customMenuProvider = CustomMenuProvider(self, self.tocView, self.canvas)
        self.tocView.setMenuProvider(self.customMenuProvider)
        self.tocView.clicked.connect(self.layerClicked)

        # 样本管理栏(右)
        self.tableView_sampleList = QtWidgets.QTableView()
        self.tableView_sampleList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_sampleList.setObjectName("tableView_sampleList")
        self.tableView_sampleList.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_sampleList.setFixedWidth(600)
        # 创建模型并设置数据
        self.model = QStandardItemModel()
        self.model.setHorizontalHeaderLabels(["名称", "类别", "误差", "查准", "查全", "IOU", "路径", "编辑"])  # 设置列头标签
        # 创建表格视图
        self.tableView_sampleList.setModel(self.model)
        self.tableView_sampleList.resizeColumnsToContents()
        # 设置 QTableView 的列头可排序
        self.tableView_sampleList.horizontalHeader().setSectionsClickable(True)
        self.tableView_sampleList.horizontalHeader().setSortIndicatorShown(True)
        # 事件绑定
        self.tableView_sampleList.doubleClicked.connect(self.on_tableView_double_clicked)

        self.editTempLayer : QgsVectorLayer = None #初始编辑图层为None

        # 按钮
        self.actionNewProject = QAction("新建工程", self)
        self.actionOpenProject = QAction("打开工程", self)
        self.actionSaveProject = QAction("保存工程", self)
        self.actionEditSample = QAction("编辑矢量", self)
        self.actionSelectSample = QAction("选择要素", self)
        self.actionDrawPolygon = QAction("画多边形", self)
        self.actionDeleteSample = QAction("删除要素", self)
        self.actionMakeSample = QAction("样本制作", self)
        self.actionEvalSample = QAction("样本评估", self)
        self.actionImportSample = QAction("样本导入", self)
        self.actionDeleteSamples = QAction("样本删除", self)
        self.actionCloseSamples = QAction("样本关闭", self)
        self.actionQuerySample = QAction("样本查询", self)
        self.actionModelTrain = QAction("模型训练", self)
        self.actionStopTrain = QAction("终止训练", self)
        self.actionWatchTrain = QAction("监视训练", self)
        self.actionOpenRas = QAction("打开影像", self)
        self.actionOpenVec = QAction("打开矢量", self)
        self.actionZoomIn = QAction("放大工具", self)
        self.actionZoomOut = QAction("缩小工具", self)
        self.actionPan = QAction("平移工具", self)
        self.actionFullExtent = QAction("全图工具", self)  
        self.actionSelectFeature = QAction("选择要素",self) 
        self.actionDrawRect = QAction("画矩形", self)    
        self.actionClearDraw = QAction("清绘", self)
        self.actionSegment = QAction("地物提取", self)
        self.actionPostClump = QAction("聚类", self)
        self.actionRasterToVector = QAction("栅格转矢量", self)
        self.actionAbout = QAction("关于", self)
        self.setIcons()# 设置工具栏按钮图标

        self.actionZoomIn.setCheckable(True)#QAction对象设置为可选中状态
        self.actionZoomOut.setCheckable(True)
        self.actionPan.setCheckable(True)
        self.actionSelectFeature.setCheckable(True)
        self.actionStopTrain.setEnabled(False)
        self.actionWatchTrain.setEnabled(False)
        self.actionEditSample.setCheckable(True)
        self.actionEditSample.setEnabled(False)
        self.actionSelectSample.setCheckable(True)
        self.actionCloseSamples.setEnabled(False)

        # 绑定事件
        self.actionNewProject.triggered.connect(self.newProject)
        self.actionOpenProject.triggered.connect(self.openProject)
        self.actionSaveProject.triggered.connect(self.saveProject)
        self.actionOpenRas.triggered.connect(self.openDialogRas)
        self.actionOpenVec.triggered.connect(self.openDialogVec)
        self.actionZoomIn.triggered.connect(self.zoomIn)
        self.actionZoomOut.triggered.connect(self.zoomOut)
        self.actionPan.triggered.connect(self.pan)
        self.actionFullExtent.triggered.connect(self.fullExtent)
        self.actionEditSample.triggered.connect(self.editSample)
        self.actionDrawPolygon.triggered.connect(self.drawPolygon)
        self.actionSelectSample.triggered.connect(self.selectFeature)
        self.actionDeleteSample.triggered.connect(self.deleteSample)
        self.actionEvalSample.triggered.connect(self.evalSample)
        self.actionMakeSample.triggered.connect(self.makeSample)
        self.actionImportSample.triggered.connect(self.importSample)
        self.actionDeleteSamples.triggered.connect(self.deleteSamples)
        self.actionQuerySample.triggered.connect(self.querySample)
        self.actionCloseSamples.triggered.connect(self.closeSamples)
        self.actionModelTrain.triggered.connect(self.modelTrain)
        self.actionStopTrain.triggered.connect(self.stopTrain)
        self.actionWatchTrain.triggered.connect(self.watchTrain)
        self.actionSelectFeature.triggered.connect(self.selectFeature)
        self.actionDrawRect.triggered.connect(self.drawRect)
        self.actionClearDraw.triggered.connect(self.clearDraw)  
        self.actionSegment.triggered.connect(self.segment)
        self.actionPostClump.triggered.connect(self.postClump)
        self.actionRasterToVector.triggered.connect(self.rasterToVector) 
        self.actionAbout.triggered.connect(self.about) 

        # create the map tools
        self.toolPan = QgsMapToolPan(self.canvas)
        self.toolPan.setAction(self.actionPan)
        self.toolZoomIn = QgsMapToolZoom(self.canvas, False)  # false = in
        self.toolZoomIn.setAction(self.actionZoomIn)
        self.toolZoomOut = QgsMapToolZoom(self.canvas, True)  # true = out
        self.toolZoomOut.setAction(self.actionZoomOut)

        # 菜单栏
        menuBar = self.menuBar()# QMainWindow自带空的菜单栏、工具栏、状态栏
        fileMenu = menuBar.addMenu('文件')# 添加“文件”菜单
        viewMenu = menuBar.addMenu('视图')
        sampleMenu = menuBar.addMenu('样本')
        trainMenu = menuBar.addMenu('训练')
        processMenu = menuBar.addMenu('处理')   
        helpMenu = menuBar.addMenu('帮助')   
        fileMenu.addAction(self.actionNewProject)# 将“新建工程”菜单项添加到“文件”菜单中
        fileMenu.addAction(self.actionOpenProject) 
        fileMenu.addAction(self.actionSaveProject)  
        fileMenu.addSeparator()                  
        fileMenu.addAction(self.actionOpenRas)
        fileMenu.addAction(self.actionOpenVec)
        viewMenu.addAction(self.actionZoomIn)
        viewMenu.addAction(self.actionZoomOut)
        viewMenu.addAction(self.actionPan)
        viewMenu.addAction(self.actionFullExtent)
        sampleMenu.addAction(self.actionEditSample)
        sampleMenu.addAction(self.actionDrawPolygon)
        sampleMenu.addAction(self.actionSelectFeature)
        sampleMenu.addAction(self.actionDeleteSample)
        sampleMenu.addSeparator()  
        sampleMenu.addAction(self.actionMakeSample)
        sampleMenu.addAction(self.actionEvalSample)
        sampleMenu.addSeparator() 
        sampleMenu.addAction(self.actionImportSample)
        sampleMenu.addAction(self.actionDeleteSamples)
        sampleMenu.addAction(self.actionQuerySample)
        sampleMenu.addAction(self.actionCloseSamples)
        trainMenu.addAction(self.actionModelTrain)
        trainMenu.addAction(self.actionStopTrain)
        trainMenu.addAction(self.actionWatchTrain)
        processMenu.addAction(self.actionSelectFeature)
        processMenu.addAction(self.actionDrawRect)
        processMenu.addAction(self.actionClearDraw)
        processMenu.addSeparator()
        processMenu.addAction(self.actionSegment)
        processMenu.addSeparator()
        processMenu.addAction(self.actionPostClump)
        processMenu.addAction(self.actionRasterToVector)
        helpMenu.addAction(self.actionAbout)

        # 工具栏
        toolBar = QToolBar("Canvas actions")
        self.addToolBar(toolBar)
        toolBar.addAction(self.actionNewProject)
        toolBar.addAction(self.actionOpenProject)
        toolBar.addAction(self.actionSaveProject)
        toolBar.addSeparator()
        toolBar.addAction(self.actionOpenRas)
        toolBar.addAction(self.actionOpenVec)
        toolBar.addSeparator()
        toolBar.addAction(self.actionZoomIn)
        toolBar.addAction(self.actionZoomOut)
        toolBar.addAction(self.actionPan)
        toolBar.addAction(self.actionFullExtent)
        toolBar.addSeparator() 
        toolBar.addAction(self.actionEditSample)
        toolBar.addAction(self.actionDrawPolygon)
        toolBar.addAction(self.actionSelectFeature)
        toolBar.addAction(self.actionDeleteSample)
        toolBar.addSeparator() 
        toolBar.addAction(self.actionMakeSample)
        toolBar.addAction(self.actionEvalSample)
        toolBar.addSeparator() 
        toolBar.addAction(self.actionImportSample)
        toolBar.addAction(self.actionDeleteSamples)
        toolBar.addAction(self.actionQuerySample)
        toolBar.addAction(self.actionCloseSamples)
        toolBar.addSeparator() 
        toolBar.addAction(self.actionModelTrain) 
        toolBar.addAction(self.actionStopTrain)    
        toolBar.addAction(self.actionWatchTrain)  
        toolBar.addSeparator() 
        toolBar.addAction(self.actionSelectFeature)   
        toolBar.addAction(self.actionDrawRect)
        from tools.RectangleMapTool import RectangleMapTool
        self.toolDrawRect = RectangleMapTool(self.canvas)       
        toolBar.addAction(self.actionClearDraw)
        toolBar.addSeparator()
        toolBar.addAction(self.actionSegment)  
        toolBar.addSeparator()   
        toolBar.addAction(self.actionPostClump)
        toolBar.addAction(self.actionRasterToVector)      
           
        # 状态栏
        statusBar = self.statusBar()  # 确保状态栏被创建
        statusBar.setSizeGripEnabled(False)  # 禁用大小调整手柄       
        self.progress_bar = QLabel(self)# 创建用于显示处理进度的进度条  
        self.coordinate_label = QLabel('{:<40}'.format(''))# 创建用于显示坐标信息的标签  #x y 坐标状态   
        self.crs_label = QLabel(f"坐标系: {self.canvas.mapSettings().destinationCrs().description()}")
        self.canvas.destinationCrsChanged.connect(self.showCrs)
        # 将进度条和标签添加到水平布局中
        layout = QHBoxLayout()
        layout.addWidget(self.progress_bar)
        layout.addStretch(1)  # 添加一个可伸缩的空间，使标签右对齐
        layout.addWidget(self.crs_label)
        layout.addWidget(self.coordinate_label)
        layout.setSpacing(5)  # 设置小部件之间的间距
        layout.setContentsMargins(0, 0, 0, 0)  # 设置布局的边距为0
        # 创建一个容器小部件来包含布局
        container = QWidget()
        container.setLayout(layout)
        # 将容器小部件添加到状态栏中
        statusBar.addWidget(container, 1)  # 1表示伸展因子，使容器占据剩余空间
        # 为容器小部件设置样式表以添加边框
        container.setStyleSheet("""
            QWidget {               
                padding: 5px; /* 设置内边距为5像素 */
            }
        """)

        # 主窗口布局
        centralWidget = QWidget()
        hLayout = QHBoxLayout()
        hLayout.addWidget(self.tocView)
        hLayout.addWidget(self.canvas)
        hLayout.addWidget(self.tableView_sampleList)
        centralWidget.setLayout(hLayout)
        self.setCentralWidget(centralWidget)

        self.pan()# 设置默认功能          

    def zoomIn(self):
        self.canvas.setMapTool(self.toolZoomIn)

    def zoomOut(self):
        self.canvas.setMapTool(self.toolZoomOut)

    def pan(self):
        self.canvas.setMapTool(self.toolPan)

    def fullExtent(self):
        self.canvas.zoomToFullExtent()

    def layerClicked(self):
        curLayer: QgsMapLayer = self.tocView.currentLayer()
        if curLayer and type(curLayer) == QgsVectorLayer and not curLayer.readOnly():
            self.actionEditSample.setEnabled(True)
        else:
            self.actionEditSample.setEnabled(False)

    def editSample(self):
        if self.actionEditSample.isChecked():
            self.editTempLayer : QgsVectorLayer = self.tocView.currentLayer()
            self.editTempLayer.startEditing()
        else:
            saveShpEdit = QMessageBox.question(self, '保存编辑', "确定要将编辑内容保存到内存吗？", QMessageBox.Yes | QMessageBox.No,QMessageBox.No)
            if saveShpEdit == QMessageBox.Yes:
                self.editTempLayer.commitChanges()
            else:
                self.editTempLayer.rollBack()
    
            self.canvas.refresh()
            self.pan()
            self.actionEditSample.setEnabled(False)
            self.editTempLayer = None

    def drawPolygon(self):  
        from tools.PolygonMapTool import PolygonMapTool
        if self.editTempLayer == None:
            QMessageBox.warning(self, '警告', '您没有编辑中的矢量！')
            return
        if self.canvas.mapTool():
            self.canvas.mapTool().deactivate()
        self.polygonTool = PolygonMapTool(self.canvas, self.editTempLayer, self)
        self.canvas.setMapTool(self.polygonTool)

    def deleteSample(self):
        if self.editTempLayer == None:
            QMessageBox.information(self, '警告', '您没有编辑中矢量')
            return
        if len(self.editTempLayer.selectedFeatureIds()) == 0:
            QMessageBox.information(self, '删除选中矢量', '您没有选择任何矢量')
        else:
            self.editTempLayer.deleteSelectedFeatures()

    def evalSample(self):
        from dialog.EvalSampleDialog import Ui_Dialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.evalSampleDialog = QDialog(self)
        self.ui_evalSample = Ui_Dialog()
        self.ui_evalSample.setupUi(self.evalSampleDialog)
        # 显示对话框
        result = self.evalSampleDialog.exec_()  # 这会阻塞，直到对话框关闭
 
        if result == QDialog.Accepted:
            from algorithm.EvalSampleThread import EvalSampleThread
            self.thread = EvalSampleThread(self.ui_evalSample, self.progress_bar)
            self.thread.finished.connect(self.on_evalSample_finished)  # 连接信号到槽
            self.thread.start()
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    def on_evalSample_finished(self,result):
        print(result)

    def makeSample(self):
        from dialog.MakeSampleDiaolog import Ui_Dialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.makeSampleDialog = QDialog(self)
        self.ui_makeSample = Ui_Dialog()
        self.ui_makeSample.setupUi(self.makeSampleDialog)
        # 显示对话框
        result = self.makeSampleDialog.exec_()  # 这会阻塞，直到对话框关闭
 
        if result == QDialog.Accepted:
            from algorithm.MakeSampleThread import MakeSampleThread
            self.thread = MakeSampleThread(self.ui_makeSample, self.progress_bar)
            self.thread.finished.connect(self.on_makeSample_finished)  # 连接信号到槽
            self.thread.start()
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")
    
    def on_makeSample_finished(self, result):
        print(result)  # 在主线程中处理结果

    def querySample(self):
        from dialog.QuerySampleDialog import Ui_Dialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.querySampleDialog = QDialog(self)
        self.ui_querySample = Ui_Dialog()
        self.ui_querySample.setupUi(self.querySampleDialog)
        # 显示对话框
        result = self.querySampleDialog.exec_()

        if result == QDialog.Accepted:
            # 启动子线程
            from algorithm.QuerySampleThread import QuerySampleThread
            self.thread_query = QuerySampleThread(self.ui_querySample, self.progress_bar)
            self.thread_query.finished.connect(self.on_query_finished)  # 连接信号到槽
            self.thread_query.start()  
            self.actionCloseSamples.setEnabled(True)
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    def on_query_finished(self,result):
        print(result)
        import time
        from osgeo import ogr
        time_start=time.time()
        self.progress_bar.setText('开始处理...')
        samplelists = self.thread_query.sampleList
        count = len(samplelists)
        #print(count)
        for index1,sample in enumerate(samplelists):
            rangefile = sample+'SamplesRange.shp'
            driver = ogr.GetDriverByName("ESRI Shapefile")
            data_source:ogr.DataSource = driver.Open(rangefile, 0)  # 0只读模式
            if data_source is None:
                print(f"无法打开文件:{rangefile}")
                return
            else:
                layer = data_source.GetLayer()

            # 获取输入图层的几何类型和字段定义
            feature_count = layer.GetFeatureCount()
            # 遍历每个要素
            for index2,feature in enumerate(layer):
                self.progress_bar.setText(f"开始处理({index1+1}/{count}): {int((index2+1) * 100 / feature_count)}%")
                # 确定输出文件名
                name  = feature.GetField("Name")
                type = feature.GetField("Bz")
                loss = feature.GetField("Loss")
                acc = feature.GetField("Acc")
                recall = feature.GetField("Recall")
                iou = feature.GetField("Iou")
                path = feature.GetField("Path")
                checkbox_item = QStandardItem()
                checkbox_item.setCheckable(True)
                #checkbox_item.setCheckState(Qt.Unchecked)  # 可选：设置初始检查状态                               
                row = [QStandardItem(name), QStandardItem(type), QStandardItem(loss), QStandardItem(acc), QStandardItem(recall), QStandardItem(iou), QStandardItem(path), checkbox_item]
                self.model.appendRow(row)
        self.tableView_sampleList.resizeColumnsToContents()
        time_end = time.time()
        self.progress_bar.setText(f"处理完成: 花费时间 {((time_end-time_start)/60.0):.2f} 分钟")

    def importSample(self):
        from dialog.ImportSamplesDialog import Ui_Dialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.importSampleDialog = QDialog(self)
        self.ui_importSample = Ui_Dialog()
        self.ui_importSample.setupUi(self.importSampleDialog)
        # 显示对话框
        result = self.importSampleDialog.exec_()

        if result == QDialog.Accepted:
            from lxml import etree
            parser = etree.XMLParser(remove_blank_text=True)  # 移除空白文本节点
            # XML文件的路径
            from DeeplearningSystem import sample_cofing_path
            # 加载现有 XML
            tree = etree.parse(sample_cofing_path, parser)
        
            # 查找特定ID的节点
            nodes = tree.xpath(f'//SamplePath[@Name="{self.ui_importSample.lineEdit_labelName.text()}"]')
            if not nodes:
                node1 = tree.xpath(f'//SampleClass[@EnglishName="{self.ui_importSample.lineEdit_Class.text()}"]')[0]
                # 创建新节点
                new_node = etree.SubElement(node1, 'SamplePath', 
                                            attrib={'Type': self.ui_importSample.lineEdit_labelType.text(),
                                                    'Size': self.ui_importSample.lineEdit_labelSize.text(),
                                                    'GSD': self.ui_importSample.lineEdit_labelGSD.text(),
                                                    'Acc': self.ui_importSample.lineEdit_labelAcc.text(),
                                                    'Recall': self.ui_importSample.lineEdit_labelRecall.text(),
                                                    'IOU': self.ui_importSample.lineEdit_labelIOU.text(),
                                                    'Name': self.ui_importSample.lineEdit_labelName.text(),
                                                    'ValSetNums': self.ui_importSample.lineEdit_labelValNums.text()
                                                    }).text = self.ui_importSample.lineEdit_SamplesPath.text()+"/"
            else:
                node = nodes[0]
                saveSample = QMessageBox.question(self, '样本导入', "存在相同的样本，确定要导入吗？\n如果导入,将会覆盖！", QMessageBox.Yes | QMessageBox.No,QMessageBox.No)
                if saveSample == QMessageBox.Yes:
                    node.text = self.ui_importSample.lineEdit_SamplesPath.text()+"/"  # 更新文本内容
                else:
                    return
            # 保存修改
            tree.write(sample_cofing_path, 
                    encoding='utf-8', 
                    xml_declaration=True, 
                    pretty_print=True)      
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    # 删除样本库
    def deleteSamples(self):
        from dialog.DeleteSamplesDialog import Ui_Dialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.deleteSamplesDialog = QDialog(self)
        self.ui_deleteSamples = Ui_Dialog()
        self.ui_deleteSamples.setupUi(self.deleteSamplesDialog)
        # 显示对话框
        result = self.deleteSamplesDialog.exec_()

        if result == QDialog.Accepted:
            from lxml import etree
            # XML文件的路径
            from DeeplearningSystem import sample_cofing_path
            # 加载现有 XML
            tree = etree.parse(sample_cofing_path)

            column_index = 4  # 假设复选框项在第三列（索引为4）
            for row_index in range(self.ui_deleteSamples.model.rowCount()):                  
                check_state = self.ui_deleteSamples.model.item(row_index, column_index).checkState()
                if check_state == Qt.Checked:
                    name = self.ui_deleteSamples.sampleList[row_index]
                    # 查找特定ID的节点
                    try:
                        # 尝试获取节点
                        node = tree.xpath(f'//SamplePath[@Name="{name}"]')[0]
                        if node is not None:
                            deleteSample = QMessageBox.question(self, '删除样本库', f"确定要删除名称为“{name}”的样本库吗？", QMessageBox.Yes | QMessageBox.No,QMessageBox.No)
                            if deleteSample == QMessageBox.Yes:
                                node.getparent().remove(node)
                            else:
                                return                                
                    except IndexError:
                        print("未找到匹配的节点")
                    except etree.XPathEvalError as e:
                        print(f"XPath表达式错误: {e}")
                    except Exception as e:
                        print(f"发生错误: {e}")
                    # 保存修改
                    tree.write(sample_cofing_path, 
                            encoding='utf-8', 
                            xml_declaration=True, 
                            pretty_print=True)

    # 关闭样本库
    def closeSamples(self):
        self.model.removeRows(0,self.model.rowCount())
        self.tableView_sampleList.resizeColumnsToContents()
        self.actionCloseSamples.setEnabled(False)

    def on_tableView_double_clicked(self, index):
        row = index.row()
        name_index = index.sibling(row, 0)
        name = name_index.data()
        path_index = index.sibling(row, 6)  # 获取同一行的其他列索引
        path = path_index.data()  # 获取单元格数据
        image_file = f'{path}/image/{name}.tif'
        shape_file = f'{path}/vector/{name}.shp'
        #print(image_file,shape_file)
        self.addRaster(image_file)
        self.addVector(shape_file)

    def modelTrain(self):
        from dialog.TrainDialog import Ui_Dialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.dialog = QDialog(self)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.dialog)
        # 显示对话框
        result = self.dialog.exec_()  # 这会阻塞，直到对话框关闭
 
        if result == QDialog.Accepted:
            self.actionStopTrain.setEnabled(True)
            self.actionWatchTrain.setEnabled(True)
            # sample
            lines_train = []
            train_nums = 0
            lines_val = []
            val_nums = 0
            column_index = 4  # 假设复选框项在第三列（索引为4）
            for row_index in range(self.ui.model.rowCount()):                  
                check_state = self.ui.model.item(row_index, column_index).checkState()
                if check_state == Qt.Checked:
                    samplerange_file = self.ui.sampleList[row_index]+'SamplesRange.shp'
                    from osgeo import ogr
                    driver = ogr.GetDriverByName("ESRI Shapefile")
                    data_source:ogr.DataSource = driver.Open(samplerange_file, 0)  # 0只读模式
                    if data_source is None:
                        print("无法打开文件")
                    else:
                        layer = data_source.GetLayer()
                    for feature in layer:
                        bz_vale = feature.GetField("Bz")
                        name_value = feature.GetField("Name")
                        path_value = feature.GetField("Path")
                        sample = f'{path_value}/image/{name_value}.tif\n'
                        if bz_vale == "train":
                            lines_train.append(sample)
                            train_nums+=1
                        else:
                            lines_val.append(sample)
                            val_nums+=1
                    data_source.Release()
            from DeeplearningSystem import train_set,val_set
            with open(train_set, 'w', encoding='utf-8') as file:
                file.write(f'{train_nums}\n')
                file.writelines(lines_train)
            with open(val_set, 'w', encoding='utf-8') as file:
                file.write(f'{val_nums}\n')
                file.writelines(lines_val)
            # 初始化日志监视对话框
            from dialog.LogDialog import Ui_Dialog as LogDialog     
            self.log_dialog = QDialog(self)
            self.ui_log = LogDialog()
            self.ui_log.setupUi(self.log_dialog)    
            # 启动训练子线程
            from algorithm.TrainThread import TrainThread
            self.thread_train = TrainThread(self.ui, self.progress_bar)
            self.thread_train.finished.connect(self.on_train_finished)  # 连接信号到槽
            self.thread_train.msg.connect(self.on_train_msg)  # 连接信号到槽
            self.thread_train.start()                       
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    def on_train_finished(self, result):
        QMessageBox.information(self, '提示', f"训练完成！", QMessageBox.Ok)

    def on_train_msg(self, result):
        self.ui_log.textEdit_Log.append(result)

    def stopTrain(self):  
        result = QMessageBox.question(self, '信息', "确定要终止训练？", QMessageBox.Yes | QMessageBox.No,
                                        QMessageBox.No)
        if result == QMessageBox.Yes:
            self.thread_train.stop()

    def watchTrain(self):                    
        # 显示对话框
        self.log_dialog.show()
     
    def selectFeature(self):
        if self.actionSelectFeature.isChecked():
            if self.canvas.mapTool():
                self.canvas.unsetMapTool(self.canvas.mapTool())
            self.toolSelectFeature = QgsMapToolIdentifyFeature(self.canvas)
            self.toolSelectFeature.setAction(self.actionSelectFeature)
            self.toolSelectFeature.setCursor(Qt.ArrowCursor)
            self.toolSelectFeature.featureIdentified.connect(self.selectToolIdentified)
            layers = self.canvas.layers()
            if layers:
                self.toolSelectFeature.setLayer(self.tocView.currentLayer())
            self.canvas.setMapTool(self.toolSelectFeature)
        else:
            if self.canvas.mapTool():
                self.canvas.unsetMapTool(self.canvas.mapTool())

    def selectToolIdentified(self,feature):
        #print(feature.id())
        layerTemp: QgsVectorLayer = self.tocView.currentLayer()
        if layerTemp.type() == QgsMapLayerType.VectorLayer:
            if feature.id() in layerTemp.selectedFeatureIds():
                layerTemp.deselect(feature.id())
            else:
                layerTemp.removeSelection()
                layerTemp.select(feature.id())

    def drawRect(self):  
        from tools.RectangleMapTool import RectangleMapTool
        self.toolDrawRect = RectangleMapTool(self.canvas)
        self.toolDrawRect.setAction(self.actionDrawRect)
        self.canvas.setMapTool(self.toolDrawRect)

    def clearDraw(self):  
        self.toolDrawRect.reset()    
        self.canvas.scene().removeItem(self.toolDrawRect.rubberBand)
        self.pan()

    def about(self):
        import datetime,json
        from cryptography.fernet import Fernet
        from DeeplearningSystem import key_path,lic_path
        # 从文件加载密钥
        with open(key_path, 'rb') as key_file:
            key = key_file.read()           
        # 创建Fernet对象
        fernet = Fernet(key)
        with open(lic_path, "rb") as f:
            encrypted_license = f.read()         
        license_json = fernet.decrypt(encrypted_license).decode()
        license_data = json.loads(license_json)
        software_version = license_data.get("software_version")
        user_id = license_data.get("user_id")
        expiration_date = license_data.get("expiration_date")
        QMessageBox.information(self, '提示', 
                                f'软件信息：基于深度学习的遥感影像信息提取系统\n构建日期：2024-12-31\n版权所有：河南省地球物理空间信息研究院有限公司\n技术邮箱：malianwei2009@163.com\n许可截至：{expiration_date}',
                                  QMessageBox.Ok)
    # 栅格转矢量
    def rasterToVector(self):
        from dialog.RasterToVectorDialog import Ui_Dialog
        from qgis.PyQt.QtWidgets import QDialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.dialog = QDialog(self)
        self.ui_raserToVector = Ui_Dialog()
        self.ui_raserToVector.setupUi(self.dialog)
        # 显示对话框
        result = self.dialog.exec_()  # 这会阻塞，直到对话框关闭
 
        if result == QDialog.Accepted:
            from algorithm.RasterToVectorThread import RasterToVectorThread
            self.thread = RasterToVectorThread(self.ui_raserToVector, self.progress_bar)
            self.thread.finished.connect(self.on_rasterToVector_finished)  # 连接信号到槽
            self.thread.start()
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    def on_rasterToVector_finished(self, result):
        print(result)  # 在主线程中处理结果
        self.addVector(result)

    # 分类后处理-聚类
    def postClump(self):
        from dialog.PostProcessDialog import Ui_Dialog
        from qgis.PyQt.QtWidgets import QDialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.dialog = QDialog(self)
        self.ui_postProcessDialog = Ui_Dialog()
        self.ui_postProcessDialog.setupUi(self.dialog)
        # 显示对话框
        result = self.dialog.exec_()  # 这会阻塞，直到对话框关闭
 
        if result == QDialog.Accepted:
            from algorithm.PostClumpThread import PostClumpThread
            self.thread = PostClumpThread(self.ui_postProcessDialog, self.progress_bar, self.toolDrawRect)
            self.thread.finished.connect(self.on_postclump_finished)  # 连接信号到槽
            self.thread.start()
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    def on_postclump_finished(self, result):
        print(result)  # 在主线程中处理结果
        self.addRaster(result)

    #######
    def setIcons(self):
        # 获取当前脚本所在的目录
        from DeeplearningSystem import base_dir   
        # 设置图标
        icon_mainWindow = QIcon()
        icon_mainWindow_path = join(base_dir, 'settings/icon', 'mainWindow.png')
        icon_mainWindow.addPixmap(QPixmap(icon_mainWindow_path), QIcon.Normal, QIcon.Off)
        self.setWindowIcon(icon_mainWindow)

        icon_newProject = join(base_dir, 'settings/icon', 'SystemProject_NewProject.png')# 替换为你的图标文件路径
        self.actionNewProject.setIcon(QIcon(icon_newProject))

        icon_openProject = join(base_dir, 'settings/icon', 'SystemProject_OpenProject.png')
        self.actionOpenProject.setIcon(QIcon(icon_openProject))

        icon_saveProject = join(base_dir, 'settings/icon', 'SystemProject_SaveProject.png')
        self.actionSaveProject.setIcon(QIcon(icon_saveProject))

        icon_openImage = join(base_dir, 'settings/icon', 'DataLoader_Raster.png')
        self.actionOpenRas.setIcon(QIcon(icon_openImage))

        icon_openVector = join(base_dir, 'settings/icon', 'DataLoader_Vector.png')
        self.actionOpenVec.setIcon(QIcon(icon_openVector))

        icon_zoomIn = join(base_dir, 'settings/icon', 'MapBrowser_ZoomIn.png') 
        self.actionZoomIn.setIcon(QIcon(icon_zoomIn))

        icon_zoomOut = join(base_dir, 'settings/icon', 'MapBrowser_ZoomOut.png')
        self.actionZoomOut.setIcon(QIcon(icon_zoomOut))

        icon_Pan = join(base_dir, 'settings/icon', 'MapBrowser_Pan.png')
        self.actionPan.setIcon(QIcon(icon_Pan))

        icon_FullExten = join(base_dir, 'settings/icon', 'MapBrowser_FullExtent.png')
        self.actionFullExtent.setIcon(QIcon(icon_FullExten))

        icon_EditSample = join(base_dir, 'settings/icon', 'VectorEditor_Edit.png')
        self.actionEditSample.setIcon(QIcon(icon_EditSample))

        icon_DrawPolygon = join(base_dir, 'settings/icon', 'VectorEditor_DrawPolygonFeature.png')
        self.actionDrawPolygon.setIcon(QIcon(icon_DrawPolygon))

        icon_SelectSample = join(base_dir, 'settings/icon', 'VectorEditor_SelectFeature.png')
        self.actionSelectSample.setIcon(QIcon(icon_SelectSample))

        icon_DeleteSample = join(base_dir, 'settings/icon', 'VectorEditor_AddFeature.png')
        self.actionDeleteSample.setIcon(QIcon(icon_DeleteSample))

        icon_MakeSample = join(base_dir, 'settings/icon', 'MakeSample.png')
        self.actionMakeSample.setIcon(QIcon(icon_MakeSample))

        icon_EvaleSample = join(base_dir, 'settings/icon', 'Sample_Evalue.png')
        self.actionEvalSample.setIcon(QIcon(icon_EvaleSample))

        icon_ImportSample = join(base_dir, 'settings/icon', 'label_import.png')
        self.actionImportSample.setIcon(QIcon(icon_ImportSample))

        icon_DeleteSamples = join(base_dir, 'settings/icon', 'label_delete.png')
        self.actionDeleteSamples.setIcon(QIcon(icon_DeleteSamples))

        icon_QuerySample = join(base_dir, 'settings/icon', 'Query.png')
        self.actionQuerySample.setIcon(QIcon(icon_QuerySample))

        icon_CloseSamples = join(base_dir, 'settings/icon', 'label_close.png')
        self.actionCloseSamples.setIcon(QIcon(icon_CloseSamples))

        icon_StartTrain = join(base_dir, 'settings/icon', 'Train_Start.png')
        self.actionModelTrain.setIcon(QIcon(icon_StartTrain))

        icon_StopTrain = join(base_dir, 'settings/icon', 'Train_Stop.png')
        self.actionStopTrain.setIcon(QIcon(icon_StopTrain))

        icon_WatchTrain = join(base_dir, 'settings/icon', 'Train_Watch.png')
        self.actionWatchTrain.setIcon(QIcon(icon_WatchTrain))
        
        icon_SeclectFeature = join(base_dir, 'settings/icon', 'MarkTool_SelectElement.png')
        self.actionSelectFeature.setIcon(QIcon(icon_SeclectFeature))

        icon_DrawRect = join(base_dir, 'settings/icon', 'MarkTool_DrawRectElement.png')
        self.actionDrawRect.setIcon(QIcon(icon_DrawRect))       
        
        icon_ClearDraw = join(base_dir, 'settings/icon', 'MainCategory_DeleteAllSelect.png')  
        self.actionClearDraw.setIcon(QIcon(icon_ClearDraw))       

        icon_Segment = join(base_dir, 'settings/icon', 'Segment.png') 
        self.actionSegment.setIcon(QIcon(icon_Segment))

        icon_PostClump = join(base_dir, 'settings/icon', 'ImgClass_Post_Clump.png') 
        self.actionPostClump.setIcon(QIcon(icon_PostClump))
        
        icon_RasterToVector = join(base_dir, 'settings/icon', 'Utility_RasterToVector.png')
        self.actionRasterToVector.setIcon(QIcon(icon_RasterToVector))

        icon_About = join(base_dir, 'settings/icon', 'MainCategory_About.png')
        self.actionAbout.setIcon(QIcon(icon_About))
    
    # 新建工程
    def newProject(self):
        # 创建一个新的项目
        project = QgsProject.instance()
        project.clear()  # 清除当前项目中的所有内容（如果有的话）
        
        # 设置项目的CRS（可选）
        # 例如，使用WGS 84坐标系统
        crs = QgsCoordinateReferenceSystem()
        crs.createFromId(4326, QgsCoordinateReferenceSystem.EpsgCrsId)
        project.setCrs(crs)
        
        # 保存新项目到文件（例如：new_project.qgs）
        from DeeplearningSystem import base_dir
        project_path = join(base_dir, 'temp', 'new_project.qgs')
        project.writeEntry("qgis", "/projectTitle", "New Project")  # 设置项目标题（可选）
        project.setFileName(project_path)
        project.write()

        self.setWindowTitle("new_project.qgs - 基于深度学习的遥感影像提取系统") 

    # 保存工程
    def saveProject(self):
        path_to_project = self.windowTitle().split(" - ")[0]
        # 获取当前项目实例
        project = QgsProject.instance() 
        if path_to_project == "new_project.qgs":
            path_to_project,_ = QFileDialog.getSaveFileName (self, '保存工程', '', 'Project File (*.qgs);;All Files (*.*)')
            if  path_to_project == "":# 如果用户取消了选择，则返回空字符串
                return               
            # 设置要保存的文件路径和文件名
            #project.setFileName(path_to_project)   
            # 保存项目到指定文件
            project.write(path_to_project)
            self.setWindowTitle(f"{basename(path_to_project)} - 基于深度学习的遥感影像提取系统") 
        else:
            project.write()

    # 打开工程
    def openProject(self):
        path_to_project,_ = QFileDialog.getOpenFileName (self, '打开工程', '', 'Project File (*.qgs);;All Files (*.*)')
        if  path_to_project == "":# 如果用户取消了选择，则返回空字符串
            return
        self.addProject(path_to_project)  

    # 打开影像
    def openDialogRas(self):
        path_to_tif,_ = QFileDialog.getOpenFileName(self, '打开', '', 'Raster Files (*.tif;*.tiff;*.img;*.dat);;All Files (*.*)')
        if  path_to_tif=="":# 如果用户取消了选择，则返回空字符串
            return
        self.addRaster(path_to_tif)

    # 打开矢量
    def openDialogVec(self):
        path_to_vec, _ = QFileDialog.getOpenFileName(self, '打开', '', 'Vector Files (*.shp);;All Files (*.*)')
        if  path_to_vec=="":
            return
        self.addVector(path_to_vec)
         
    # 信息提取
    def segment(self, path):
        #QMessageBox.information(self, '提示', '信息提取！', QMessageBox.Ok)
        from dialog.SegmentDialog import Ui_Dialog
        from qgis.PyQt.QtWidgets import QDialog
        # 创建一个对话框实例，这里我们假设对话框是基于 QDialog 的
        self.dialog = QDialog(self)
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.dialog)
        # 显示对话框
        result = self.dialog.exec_()  # 这会阻塞，直到对话框关闭
 
        if result == QDialog.Accepted:
            from algorithm.PredictThread import PredictThread
            self.thread = PredictThread(self.ui, self.progress_bar, self.toolDrawRect)
            self.thread.finished.connect(self.on_segment_finished)  # 连接信号到槽
            self.thread.start()    
        elif result == QDialog.Rejected:
            print("User clicked Close or pressed Escape")

    def on_segment_finished(self, result):
        print(result)  # 在主线程中处理结果
        self.addRaster(result)

    def addRaster(self, path):
        layer = QgsRasterLayer(path,basename(path))
        if not layer.isValid():
            QMessageBox.information(self, '提示', '文件打开失败', QMessageBox.Ok)
            return
        if self.firstAddLayer:
            self.canvas.setDestinationCrs(layer.crs())
            self.canvas.setExtent(layer.extent())
        #layer.dataProvider().setNoDataValue(1,0)
        while(QgsProject.instance().mapLayersByName(layer.name())):
            layer.setName(layer.name()+"_1")
        QgsProject.instance().addMapLayer(layer)
        layers = [layer] + [QgsProject.instance().mapLayer(i) for i in QgsProject.instance().mapLayers()]
        self.canvas.setLayers(layers)
        
        self.canvas.refresh()
        self.firstAddLayer = False
    
    def addVector(self, path):
        layer = QgsVectorLayer(path,basename(path))
        if not layer.isValid():
            QMessageBox.information(self, '提示', '文件打开失败', QMessageBox.Ok)
            return   

        # 构造一个嵌入的渲染器
        from qgis.core import QgsFillSymbol, QgsSingleSymbolRenderer,QgsInvertedPolygonRenderer
        from qgis.PyQt.QtGui import QColor
        fill_props = {}
        fill_props["color"] = QColor(0, 0, 0, 0)
        fill_props["color_border"] = 'red'
        fill = QgsFillSymbol.createSimple(fill_props)
        embededRenderer = QgsSingleSymbolRenderer(fill)

        # 构造 QgsInvertedPolygonRenderer，并赋给多边形图层
        renderer = QgsInvertedPolygonRenderer(embededRenderer)
        layer.setRenderer(renderer)

        if self.firstAddLayer:
            self.canvas.setDestinationCrs(layer.crs())
            self.canvas.setExtent(layer.extent())
        #layer.dataProvider().setNoDataValue(1,0)
        while(QgsProject.instance().mapLayersByName(layer.name())):
            layer.setName(layer.name()+"_1")
        QgsProject.instance().addMapLayer(layer)
        layers = [layer] + [QgsProject.instance().mapLayer(i) for i in QgsProject.instance().mapLayers()]
        self.canvas.setLayers(layers)

        self.canvas.refresh()
        self.firstAddLayer = False

    def addProject(self, path):
        # 获取 QgsProject 的实例
        project = QgsProject.instance()             
        # 尝试加载工程文件
        success = project.read(path)
        # 检查加载是否成功
        if not success:
            print(f"Failed to load project: {path}")
        else:
            print("Project loaded successfully")
        self.setWindowTitle(f"{basename(path)} - 基于深度学习的遥感影像提取系统") 
        QgsLayerTreeMapCanvasBridge(project.layerTreeRoot(), self.canvas)        

    def showXY(self,point):
        x = point.x()
        y = point.y()
        self.coordinate_label.setText(f'{x:.6f}, {y:.6f}')
        #self.coordinate_label.setText("Coordinate:"+str(point.x())+","+str(point.y()))

    def dragEnterEvent(self, fileData):
        if fileData.mimeData().hasUrls():
            fileData.accept()
        else:
            fileData.ignore()

    # 拖拽文件事件
    def dropEvent(self,fileData):
        mimeData: QMimeData = fileData.mimeData()
        filePathList = [u.path()[1:] for u in mimeData.urls()]
        for filePath in filePathList:
            filePath:str = filePath.replace("/","//")
            if filePath.split(".")[-1] in ["tif","TIF","tiff","TIFF","GTIFF","png","jpg","pdf","img"]:
                self.addRaster(filePath)
            elif filePath.split(".")[-1] in ["shp","SHP","gpkg","geojson","kml"]:
                self.addVector(filePath)
            elif filePath.split(".")[-1] in ["qgs"]:
                self.addProject(filePath)
            elif filePath == "":
                pass
            else:
                QMessageBox.about(self, '警告', f'{filePath}为不支持的文件类型，目前支持栅格影像和shp矢量')

    def showCrs(self):
        mapSetting : QgsMapSettings = self.canvas.mapSettings()
        self.crs_label.setText(f"坐标系: {mapSetting.destinationCrs().description()}")
            
            