# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layerPropWindow.ui'
#
# Created by: qgis.PyQt UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.core import QgsVectorLayer,QgsRasterLayer,QgsStyle,QgsRasterDataProvider,QgsVectorDataProvider,QgsRectangle,QgsCoordinateReferenceSystem,QgsWkbTypes
from qgis.gui import QgsRendererRasterPropertiesWidget,QgsSingleSymbolRendererWidget,QgsCategorizedSymbolRendererWidget
from qgis.PyQt.QtWidgets import QDialog,QListWidgetItem,QTabBar
import os.path as osp


class Ui_LayerProp(object):
    def setupUi(self, LayerProp):
        LayerProp.setObjectName("LayerProp")
        LayerProp.resize(638, 425)
        LayerProp.setWindowFlags(LayerProp.windowFlags() & ~(QtCore.Qt.WindowContextHelpButtonHint))# 隐藏对话框标题栏默认的问号按钮
        LayerProp.setMinimumSize(QtCore.QSize(638, 425))
        LayerProp.setMaximumSize(QtCore.QSize(638, 425))
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(LayerProp)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.listWidget = QtWidgets.QListWidget(LayerProp)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout_19.addWidget(self.listWidget)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(LayerProp)
        self.tabWidget.setObjectName("tabWidget")
        self.rasterLayerInfoTab = QtWidgets.QWidget()
        self.rasterLayerInfoTab.setObjectName("rasterLayerInfoTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.rasterLayerInfoTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.rasterLayerInfoTab)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.rasterLayerInfoTab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.rasterNameLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterNameLabel.setObjectName("rasterNameLabel")
        self.horizontalLayout.addWidget(self.rasterNameLabel)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.rasterSourceLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterSourceLabel.setObjectName("rasterSourceLabel")
        self.horizontalLayout_2.addWidget(self.rasterSourceLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.rasterMemoryLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterMemoryLabel.setObjectName("rasterMemoryLabel")
        self.horizontalLayout_3.addWidget(self.rasterMemoryLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_9 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.line_3 = QtWidgets.QFrame(self.rasterLayerInfoTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.rasterExtentLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterExtentLabel.setObjectName("rasterExtentLabel")
        self.horizontalLayout_4.addWidget(self.rasterExtentLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.rasterWidthLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterWidthLabel.setObjectName("rasterWidthLabel")
        self.horizontalLayout_5.addWidget(self.rasterWidthLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.rasterHeightLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterHeightLabel.setObjectName("rasterHeightLabel")
        self.horizontalLayout_6.addWidget(self.rasterHeightLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_16 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_7.addWidget(self.label_16)
        self.rasterDataTypeLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterDataTypeLabel.setObjectName("rasterDataTypeLabel")
        self.horizontalLayout_7.addWidget(self.rasterDataTypeLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_18 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_8.addWidget(self.label_18)
        self.rasterBandNumLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterBandNumLabel.setObjectName("rasterBandNumLabel")
        self.horizontalLayout_8.addWidget(self.rasterBandNumLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_20 = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.label_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_9.addWidget(self.label_20)
        self.rasterCrsLabel = QtWidgets.QLabel(self.rasterLayerInfoTab)
        self.rasterCrsLabel.setObjectName("rasterCrsLabel")
        self.horizontalLayout_9.addWidget(self.rasterCrsLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.rasterLayerInfoTab, "")
        self.vectorLayerInfoTab = QtWidgets.QWidget()
        self.vectorLayerInfoTab.setObjectName("vectorLayerInfoTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.vectorLayerInfoTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_26 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_4.addWidget(self.label_26)
        self.line_6 = QtWidgets.QFrame(self.vectorLayerInfoTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_25 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_25.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_21.addWidget(self.label_25)
        self.vectorNameLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorNameLabel.setObjectName("vectorNameLabel")
        self.horizontalLayout_21.addWidget(self.vectorNameLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_32 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_32.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_27.addWidget(self.label_32)
        self.vectorSourceLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorSourceLabel.setObjectName("vectorSourceLabel")
        self.horizontalLayout_27.addWidget(self.vectorSourceLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_30 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_30.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_25.addWidget(self.label_30)
        self.vectorMemoryLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorMemoryLabel.setObjectName("vectorMemoryLabel")
        self.horizontalLayout_25.addWidget(self.vectorMemoryLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_25)
        self.label_34 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_4.addWidget(self.label_34)
        self.line_5 = QtWidgets.QFrame(self.vectorLayerInfoTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_4.addWidget(self.line_5)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_27 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_27.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_22.addWidget(self.label_27)
        self.vectorExtentLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorExtentLabel.setObjectName("vectorExtentLabel")
        self.horizontalLayout_22.addWidget(self.vectorExtentLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_33 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_33.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_28.addWidget(self.label_33)
        self.vectorGeoTypeLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorGeoTypeLabel.setObjectName("vectorGeoTypeLabel")
        self.horizontalLayout_28.addWidget(self.vectorGeoTypeLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_31 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_26.addWidget(self.label_31)
        self.vectorFeatureNumLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorFeatureNumLabel.setObjectName("vectorFeatureNumLabel")
        self.horizontalLayout_26.addWidget(self.vectorFeatureNumLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_35 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_35.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_29.addWidget(self.label_35)
        self.vectorEncodingLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorEncodingLabel.setObjectName("vectorEncodingLabel")
        self.horizontalLayout_29.addWidget(self.vectorEncodingLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_28 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_28.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_23.addWidget(self.label_28)
        self.vectorCrsLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorCrsLabel.setObjectName("vectorCrsLabel")
        self.horizontalLayout_23.addWidget(self.vectorCrsLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_29 = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.label_29.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_24.addWidget(self.label_29)
        self.vectorDpLabel = QtWidgets.QLabel(self.vectorLayerInfoTab)
        self.vectorDpLabel.setObjectName("vectorDpLabel")
        self.horizontalLayout_24.addWidget(self.vectorDpLabel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_24)
        self.tabWidget.addTab(self.vectorLayerInfoTab, "")
        self.rasterLayerRenderTab = QtWidgets.QWidget()
        self.rasterLayerRenderTab.setObjectName("rasterLayerRenderTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rasterLayerRenderTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.rasterLayerRenderTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.rasterLayerRenderTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.layerRenderLayout = QtWidgets.QVBoxLayout()
        self.layerRenderLayout.setObjectName("layerRenderLayout")
        self.verticalLayout_3.addLayout(self.layerRenderLayout)
        self.tabWidget.addTab(self.rasterLayerRenderTab, "")
        self.vectorLayerRenderTab = QtWidgets.QWidget()
        self.vectorLayerRenderTab.setObjectName("vectorLayerRenderTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.vectorLayerRenderTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_36 = QtWidgets.QLabel(self.vectorLayerRenderTab)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_5.addWidget(self.label_36)
        self.line_7 = QtWidgets.QFrame(self.vectorLayerRenderTab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_5.addWidget(self.line_7)
        self.layerRenderLayout_2 = QtWidgets.QVBoxLayout()
        self.layerRenderLayout_2.setObjectName("layerRenderLayout_2")
        self.vecterRenderCB = QtWidgets.QComboBox(self.vectorLayerRenderTab)
        self.vecterRenderCB.setObjectName("vecterRenderCB")
        self.vecterRenderCB.addItem("")
        self.vecterRenderCB.addItem("")
        self.layerRenderLayout_2.addWidget(self.vecterRenderCB)
        self.comboTabWidget = QtWidgets.QTabWidget(self.vectorLayerRenderTab)
        self.comboTabWidget.setObjectName("comboTabWidget")
        self.singleRender = QtWidgets.QWidget()
        self.singleRender.setObjectName("singleRender")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.singleRender)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.singleRenderLayout = QtWidgets.QVBoxLayout()
        self.singleRenderLayout.setObjectName("singleRenderLayout")
        self.verticalLayout_8.addLayout(self.singleRenderLayout)
        self.comboTabWidget.addTab(self.singleRender, "")
        self.categoryRender = QtWidgets.QWidget()
        self.categoryRender.setObjectName("categoryRender")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.categoryRender)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cateRenderLayout = QtWidgets.QVBoxLayout()
        self.cateRenderLayout.setObjectName("cateRenderLayout")
        self.verticalLayout_6.addLayout(self.cateRenderLayout)
        self.comboTabWidget.addTab(self.categoryRender, "")
        self.layerRenderLayout_2.addWidget(self.comboTabWidget)
        self.verticalLayout_5.addLayout(self.layerRenderLayout_2)
        self.tabWidget.addTab(self.vectorLayerRenderTab, "")
        self.verticalLayout_7.addWidget(self.tabWidget)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.okPb = QtWidgets.QPushButton(LayerProp)
        self.okPb.setObjectName("okPb")
        self.horizontalLayout_20.addWidget(self.okPb)
        self.cancelPb = QtWidgets.QPushButton(LayerProp)
        self.cancelPb.setObjectName("cancelPb")
        self.horizontalLayout_20.addWidget(self.cancelPb)
        self.applyPb = QtWidgets.QPushButton(LayerProp)
        self.applyPb.setObjectName("applyPb")
        self.horizontalLayout_20.addWidget(self.applyPb)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)

        self.retranslateUi(LayerProp)
        self.tabWidget.setCurrentIndex(1)
        self.comboTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LayerProp)

    def retranslateUi(self, LayerProp):
        _translate = QtCore.QCoreApplication.translate
        LayerProp.setWindowTitle(_translate("LayerProp", "图层属性"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("LayerProp", "信息"))
        item = self.listWidget.item(1)
        item.setText(_translate("LayerProp", "渲染"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("LayerProp", "常规信息"))
        self.label_3.setText(_translate("LayerProp", "名称"))
        self.rasterNameLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_5.setText(_translate("LayerProp", "路径"))
        self.rasterSourceLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_7.setText(_translate("LayerProp", "大小合计"))
        self.rasterMemoryLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_9.setText(_translate("LayerProp", "栅格信息"))
        self.label_10.setText(_translate("LayerProp", "范围"))
        self.rasterExtentLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_12.setText(_translate("LayerProp", "宽度"))
        self.rasterWidthLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_14.setText(_translate("LayerProp", "高度"))
        self.rasterHeightLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_16.setText(_translate("LayerProp", "数据类型"))
        self.rasterDataTypeLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_18.setText(_translate("LayerProp", "波段数量"))
        self.rasterBandNumLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_20.setText(_translate("LayerProp", "坐标系"))
        self.rasterCrsLabel.setText(_translate("LayerProp", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rasterLayerInfoTab), _translate("LayerProp", "rasterLayerInfoTab"))
        self.label_26.setText(_translate("LayerProp", "常规信息"))
        self.label_25.setText(_translate("LayerProp", "名称"))
        self.vectorNameLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_32.setText(_translate("LayerProp", "路径"))
        self.vectorSourceLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_30.setText(_translate("LayerProp", "大小合计"))
        self.vectorMemoryLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_34.setText(_translate("LayerProp", "矢量信息"))
        self.label_27.setText(_translate("LayerProp", "范围"))
        self.vectorExtentLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_33.setText(_translate("LayerProp", "几何图形"))
        self.vectorGeoTypeLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_31.setText(_translate("LayerProp", "要素总数"))
        self.vectorFeatureNumLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_35.setText(_translate("LayerProp", "编码"))
        self.vectorEncodingLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_28.setText(_translate("LayerProp", "坐标系"))
        self.vectorCrsLabel.setText(_translate("LayerProp", "TextLabel"))
        self.label_29.setText(_translate("LayerProp", "数据源"))
        self.vectorDpLabel.setText(_translate("LayerProp", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vectorLayerInfoTab), _translate("LayerProp", "vectorLayerInfoTab"))
        self.label_2.setText(_translate("LayerProp", "图层渲染"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rasterLayerRenderTab), _translate("LayerProp", "rasterLayerRenderTab"))
        self.label_36.setText(_translate("LayerProp", "图层渲染"))
        self.vecterRenderCB.setItemText(0, _translate("LayerProp", "单一渲染"))
        self.vecterRenderCB.setItemText(1, _translate("LayerProp", "分类渲染"))
        self.comboTabWidget.setTabText(self.comboTabWidget.indexOf(self.singleRender), _translate("LayerProp", "Tab 1"))
        self.comboTabWidget.setTabText(self.comboTabWidget.indexOf(self.categoryRender), _translate("LayerProp", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.vectorLayerRenderTab), _translate("LayerProp", "vectorLayerRenderTab"))
        self.okPb.setText(_translate("LayerProp", "确认"))
        self.cancelPb.setText(_translate("LayerProp", "取消"))
        self.applyPb.setText(_translate("LayerProp", "应用"))

class LayerAttributeDialog(QDialog, Ui_LayerProp):
    def __init__(self,layer,parent=None):
        """
        # tab 信息含义：
        0 栅格信息 1 矢量信息 2 栅格图层渲染 3 矢量图层渲染
        :param layer:
        :param parent:
        """
        super(LayerAttributeDialog,self).__init__(parent)
        self.layer = layer
        self.parentWindow = parent
        self.setupUi(self)
        self.initUI()
        self.connectFunc()

    def initUI(self):
        layerbar = self.tabWidget.findChild(QTabBar)
        layerbar.hide()
        renderBar = self.comboTabWidget.findChild(QTabBar)
        renderBar.hide()
        self.listWidget.setCurrentRow(0)
        self.initInfomationTab()
        self.decideRasterNVector(0)

    def connectFunc(self):
        self.listWidget.itemClicked.connect(self.listWidgetItemClicked)
        self.okPb.clicked.connect(lambda : self.renderApplyPbClicked(needClose=True))
        self.cancelPb.clicked.connect( self.close )
        self.applyPb.clicked.connect(lambda : self.renderApplyPbClicked(needClose=False))
        self.vecterRenderCB.currentIndexChanged.connect(self.vecterRenderCBChanged)

    # 切换矢量渲染方式
    def vecterRenderCBChanged(self):
        self.comboTabWidget.setCurrentIndex(self.vecterRenderCB.currentIndex())

    def initInfomationTab(self):
        if type(self.layer) == QgsRasterLayer:
            rasterLayerDict = getRasterLayerAttrs(self.layer)
            self.rasterNameLabel.setText(rasterLayerDict['name'])
            self.rasterSourceLabel.setText(rasterLayerDict['source'])
            self.rasterMemoryLabel.setText(rasterLayerDict['memory'])
            self.rasterExtentLabel.setText(rasterLayerDict['extent'])
            self.rasterWidthLabel.setText(rasterLayerDict['width'])
            self.rasterHeightLabel.setText(rasterLayerDict['height'])
            self.rasterDataTypeLabel.setText(rasterLayerDict['dataType'])
            self.rasterBandNumLabel.setText(rasterLayerDict['bands'])
            self.rasterCrsLabel.setText(rasterLayerDict['crs'])
            self.rasterRenderWidget = QgsRendererRasterPropertiesWidget(self.layer, self.parentWindow.canvas,parent=self) 

            from qgis.PyQt.QtWidgets import QScrollArea
            # 创建滚动区域
            self.scroll_area = QScrollArea()
            # 将rasterWidget放入滚动区域
            self.scroll_area.setWidget(self.rasterRenderWidget)
            # 根据内容大小自动调整滚动区域大小
            self.scroll_area.setWidgetResizable(True)
            # 显示滚动区域
            self.scroll_area.show()

            self.layerRenderLayout.addWidget(self.scroll_area)           

        elif type(self.layer) == QgsVectorLayer:
            self.layer : QgsVectorLayer
            vectorLayerDict = getVectorLayerAttrs(self.layer)
            self.vectorNameLabel.setText(vectorLayerDict['name'])
            self.vectorSourceLabel.setText(vectorLayerDict['source'])
            self.vectorMemoryLabel.setText(vectorLayerDict['memory'])
            self.vectorExtentLabel.setText(vectorLayerDict['extent'])
            self.vectorGeoTypeLabel.setText(vectorLayerDict['geoType'])
            self.vectorFeatureNumLabel.setText(vectorLayerDict['featureNum'])
            self.vectorEncodingLabel.setText(vectorLayerDict['encoding'])
            self.vectorCrsLabel.setText(vectorLayerDict['crs'])
            self.vectorDpLabel.setText(vectorLayerDict['dpSource'])

            # single Render
            self.vectorSingleRenderWidget = QgsSingleSymbolRendererWidget(self.layer,QgsStyle.defaultStyle(),self.layer.renderer())
            self.singleRenderLayout.addWidget(self.vectorSingleRenderWidget)

            # category Render
            self.vectorCateGoryRenderWidget = QgsCategorizedSymbolRendererWidget(self.layer,QgsStyle.defaultStyle(),self.layer.renderer())
            self.cateRenderLayout.addWidget(self.vectorCateGoryRenderWidget)

    def decideRasterNVector(self,index):
        if index == 0:
            if type(self.layer) == QgsRasterLayer:
                self.tabWidget.setCurrentIndex(0)
            elif type(self.layer) == QgsVectorLayer:
                self.tabWidget.setCurrentIndex(1)
        elif index == 1:
            if type(self.layer) == QgsRasterLayer:
                self.tabWidget.setCurrentIndex(2)
            elif type(self.layer) == QgsVectorLayer:
                self.tabWidget.setCurrentIndex(3)


    def listWidgetItemClicked(self,item:QListWidgetItem):
        tempIndex = self.listWidget.indexFromItem(item).row()
        self.decideRasterNVector(tempIndex)


    def renderApplyPbClicked(self,needClose=False):
        if self.tabWidget.currentIndex() <= 1:
            print("没有在视图里，啥也不干")
        elif type(self.layer) == QgsRasterLayer:
            self.rasterRenderWidget : QgsRendererRasterPropertiesWidget
            self.rasterRenderWidget.apply()
        elif type(self.layer) == QgsVectorLayer:
            print("矢量渲染")
            #self.vectorRenderWidget : QgsSingleSymbolRendererWidget
            self.layer : QgsVectorLayer
            if self.comboTabWidget.currentIndex() == 0:
                renderer = self.vectorSingleRenderWidget.renderer()
            else:
                renderer = self.vectorCateGoryRenderWidget.renderer()
            self.layer.setRenderer(renderer)
            self.layer.triggerRepaint()
        self.parentWindow.canvas.refresh()
        if needClose:
            self.close()

qgisDataTypeDict = {
    0 : "UnknownDataType",
    1 : "Uint8",
    2 : "UInt16",
    3 : "Int16",
    4 : "UInt32",
    5 : "Int32",
    6 : "Float32",
    7 : "Float64",
    8 : "CInt16",
    9 : "CInt32",
    10 : "CFloat32",
    11 : "CFloat64",
    12 : "ARGB32",
    13 : "ARGB32_Premultiplied"
}

def getFileSize(filePath):
    fsize = osp.getsize(filePath)  # 返回的是字节大小

    if fsize < 1024:
        return f"{round(fsize, 2)}Byte"
    else:
        KBX = fsize / 1024
        if KBX < 1024:
            return f"{round(KBX, 2)}Kb"
        else:
            MBX = KBX / 1024
            if MBX < 1024:
                return f"{round(MBX, 2)}Mb"
            else:
                return f"{round(MBX/1024,2)}Gb"
            
def getRasterLayerAttrs(rasterLayer:QgsRasterLayer):

    rdp : QgsRasterDataProvider = rasterLayer.dataProvider()
    crs : QgsCoordinateReferenceSystem = rasterLayer.crs()
    extent: QgsRectangle = rasterLayer.extent()
    resDict = {
        "name" : rasterLayer.name(),
        "source" : rasterLayer.source(),
        "memory" : getFileSize(rasterLayer.source()),
        "extent" : f"min:[{extent.xMinimum():.6f},{extent.yMinimum():.6f}]; max:[{extent.xMaximum():.6f},{extent.yMaximum():.6f}]",
        "width" : f"{rasterLayer.width()}",
        "height" : f"{rasterLayer.height()}",
        "dataType" : qgisDataTypeDict[rdp.dataType(1)],
        "bands" : f"{rasterLayer.bandCount()}",
        "crs" : crs.description()
    }
    return resDict

def getVectorLayerAttrs(vectorLayer:QgsVectorLayer):
    vdp : QgsVectorDataProvider = vectorLayer.dataProvider()
    crs: QgsCoordinateReferenceSystem = vectorLayer.crs()
    extent: QgsRectangle = vectorLayer.extent()
    resDict = {
        "name" : vectorLayer.name(),
        "source" : vectorLayer.source(),
        "memory": getFileSize(vectorLayer.source()),
        "extent" : f"min:[{extent.xMinimum():.6f},{extent.yMinimum():.6f}]; max:[{extent.xMaximum():.6f},{extent.yMaximum():.6f}]",
        "geoType" : QgsWkbTypes.geometryDisplayString(vectorLayer.geometryType()),
        "featureNum" : f"{vectorLayer.featureCount()}",
        "encoding" : vdp.encoding(),
        "crs" : crs.description(),
        "dpSource" : vdp.description()
    }
    return resDict



