# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogDialog.ui'
#
# Created by: qgis.PyQt UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setModal(False)  # 对话框不是模态的，允许用户与主窗口交互
        Dialog.setWindowFlags(Dialog.windowFlags() & ~(QtCore.Qt.WindowContextHelpButtonHint)) # 隐藏对话框标题栏默认的问号按钮
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_LogFile = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_LogFile.setReadOnly(True)
        self.lineEdit_LogFile.setObjectName("lineEdit_LogFile")
        self.horizontalLayout_2.addWidget(self.lineEdit_LogFile)
        self.pushButton_SaveLog = QtWidgets.QPushButton(Dialog)
        self.pushButton_SaveLog.setObjectName("pushButton_SaveLog")
        self.horizontalLayout_2.addWidget(self.pushButton_SaveLog)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit_Log = QtWidgets.QTextEdit(Dialog)
        self.textEdit_Log.setReadOnly(True)
        self.textEdit_Log.setObjectName("textEdit_Log")
        self.verticalLayout.addWidget(self.textEdit_Log)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "训练监视"))
        self.pushButton_SaveLog.setText(_translate("Dialog", "存储"))