# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MakeSampleDiaolog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(514, 205)
        Dialog.setMinimumSize(QtCore.QSize(514, 205))
        Dialog.setMaximumSize(QtCore.QSize(514, 205))
        Dialog.setWindowFlags(Dialog.windowFlags() & ~(QtCore.Qt.WindowContextHelpButtonHint)) # 隐藏对话框标题栏默认的问号按钮
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.groupBox_SelectSample = QtWidgets.QGroupBox(Dialog)
        self.groupBox_SelectSample.setObjectName("groupBox_SelectSample")
        self.horizontalLayout_openImage = QtWidgets.QHBoxLayout(self.groupBox_SelectSample)
        self.horizontalLayout_openImage.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_openImage.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_openImage.setSpacing(6)
        self.horizontalLayout_openImage.setObjectName("horizontalLayout_openImage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_SelectSample)
        self.label.setMaximumSize(QtCore.QSize(70, 20))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_image = QtWidgets.QLineEdit(self.groupBox_SelectSample)
        self.lineEdit_image.setObjectName("lineEdit_image")
        self.horizontalLayout.addWidget(self.lineEdit_image)
        self.pushButton_OpenImageFile = QtWidgets.QPushButton(self.groupBox_SelectSample)
        self.pushButton_OpenImageFile.setMinimumSize(QtCore.QSize(71, 23))
        self.pushButton_OpenImageFile.setMaximumSize(QtCore.QSize(71, 23))
        self.pushButton_OpenImageFile.setObjectName("pushButton_OpenImageFile")
        self.pushButton_OpenImageFile.clicked.connect(self.on_openImageFile_clicked)####################
        self.horizontalLayout.addWidget(self.pushButton_OpenImageFile)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_SelectSample)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_label = QtWidgets.QLineEdit(self.groupBox_SelectSample)
        self.lineEdit_label.setObjectName("lineEdit_label")
        self.horizontalLayout_5.addWidget(self.lineEdit_label)
        self.pushButton_OpenLabelFile = QtWidgets.QPushButton(self.groupBox_SelectSample)
        self.pushButton_OpenLabelFile.setObjectName("pushButton_OpenLabelFile")
        self.pushButton_OpenLabelFile.clicked.connect(self.on_openLabelFile_clicked)####################
        self.horizontalLayout_5.addWidget(self.pushButton_OpenLabelFile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_SelectSample)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_boundary = QtWidgets.QLineEdit(self.groupBox_SelectSample)
        self.lineEdit_boundary.setObjectName("lineEdit_boundary")
        self.horizontalLayout_6.addWidget(self.lineEdit_boundary)
        self.pushButton_OpenBoundaryFile = QtWidgets.QPushButton(self.groupBox_SelectSample)
        self.pushButton_OpenBoundaryFile.setObjectName("pushButton_OpenBoundaryFile")
        self.pushButton_OpenBoundaryFile.clicked.connect(self.on_openBoundaryFile_clicked)####################
        self.horizontalLayout_6.addWidget(self.pushButton_OpenBoundaryFile)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_openImage.addLayout(self.verticalLayout_4)
        self.verticalLayoutMain.addWidget(self.groupBox_SelectSample)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_saveImage = QtWidgets.QHBoxLayout()
        self.horizontalLayout_saveImage.setObjectName("horizontalLayout_saveImage")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_saveImage.addWidget(self.label_2)
        self.lineEdit_saveSamplePath = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_saveSamplePath.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_saveSamplePath.setMaximumSize(QtCore.QSize(16777215, 10000000))
        self.lineEdit_saveSamplePath.setObjectName("lineEdit_saveSamplePath")
        self.horizontalLayout_saveImage.addWidget(self.lineEdit_saveSamplePath)
        self.pushButton_OpenSamplePath = QtWidgets.QPushButton(Dialog)
        self.pushButton_OpenSamplePath.setMinimumSize(QtCore.QSize(71, 23))
        self.pushButton_OpenSamplePath.setMaximumSize(QtCore.QSize(71, 23))
        self.pushButton_OpenSamplePath.setObjectName("pushButton_OpenSamplePath")
        self.pushButton_OpenSamplePath.clicked.connect(self.on_saveSamplePath_clicked)####################
        self.horizontalLayout_saveImage.addWidget(self.pushButton_OpenSamplePath)
        self.verticalLayout.addLayout(self.horizontalLayout_saveImage)
        self.pushButton_MakeSample = QtWidgets.QPushButton(Dialog)
        self.pushButton_MakeSample.setObjectName("pushButton_MakeSample")
        self.verticalLayout.addWidget(self.pushButton_MakeSample, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutMain.addLayout(self.verticalLayout)
        self.horizontalLayout_1.addLayout(self.verticalLayoutMain)
        self.gridLayout_3.addLayout(self.horizontalLayout_1, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_MakeSample.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "样本制作"))
        self.groupBox_SelectSample.setTitle(_translate("Dialog", "输入数据"))
        self.label.setText(_translate("Dialog", "基准影像："))
        self.pushButton_OpenImageFile.setText(_translate("Dialog", "浏览..."))
        self.label_3.setText(_translate("Dialog", "标签矢量："))
        self.pushButton_OpenLabelFile.setText(_translate("Dialog", "浏览..."))
        self.label_4.setText(_translate("Dialog", "标签范围："))
        self.pushButton_OpenBoundaryFile.setText(_translate("Dialog", "浏览..."))
        self.label_2.setText(_translate("Dialog", "保存路径："))
        self.pushButton_OpenSamplePath.setText(_translate("Dialog", "浏览..."))
        self.pushButton_MakeSample.setText(_translate("Dialog", "确定"))

        #path = "E:/DeepLearning/Samples/Desert/256x256/Sat/Meter/positive_152526_202303_49488_zy1e/"
        #self.lineEdit_image.setText('D:/Deep_Learning/DATA/neimenggu/49488/1/降位/ZY1E_VNIC_E118.7_N45.4_20230905_L1B0000649488-PAN/ZY1E_VNIC_E118.7_N45.4_20230905_L1B0000649488-MUX_fus_color.tif')
        #self.lineEdit_label.setText(path+'label_152526_49488_zy1e.shp')
        #self.lineEdit_boundary.setText(path+'boundary_152526_49488_zy1e.shp')
        #self.lineEdit_saveSamplePath.setText(path+'crop/')

    def on_openImageFile_clicked(self,Dialog):
        from PyQt5.QtWidgets import QFileDialog
        path_to_tif,_ = QFileDialog.getOpenFileName(None, '打开', '', 'Raster Files (*.tif;*.tiff;*.img;*.dat);;All Files (*.*)')
        if  path_to_tif=="":
            return
        self.lineEdit_image.setText(path_to_tif)

    def on_openLabelFile_clicked(self,Dialog):
        from PyQt5.QtWidgets import QFileDialog
        path_to_vec,_ = QFileDialog.getOpenFileName(None, '打开', '', 'Shape Files (*.shp);;All Files (*.*)')
        if  path_to_vec=="":
            return
        self.lineEdit_label.setText(path_to_vec)

    def on_openBoundaryFile_clicked(self,Dialog):
        from PyQt5.QtWidgets import QFileDialog
        path_to_vec,_ = QFileDialog.getOpenFileName(None, '打开', '', 'Shape Files (*.shp);;All Files (*.*)')
        if  path_to_vec=="":
            return
        self.lineEdit_boundary.setText(path_to_vec)

    def on_saveSamplePath_clicked(self,Dialog):
        from PyQt5.QtWidgets import QFileDialog
        folder_selected = QFileDialog.getExistingDirectory(None, "Select Folder to Save")
        if  folder_selected:
            self.lineEdit_saveSamplePath.setText(folder_selected)