# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapToolInputAttr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 122)
        Dialog.setMinimumSize(QtCore.QSize(400, 122))
        Dialog.setMaximumSize(QtCore.QSize(400, 268))
        Dialog.setWindowFlags(Dialog.windowFlags() & ~(QtCore.Qt.WindowContextHelpButtonHint)) # 隐藏对话框标题栏默认的问号按钮
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attrsLayout = QtWidgets.QVBoxLayout()
        self.attrsLayout.setObjectName("attrsLayout")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        #self.scrollAreaWidgetContents = QtWidgets.QWidget()
        #self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 378, 215))
        #self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget_2 = QtWidgets.QWidget()#self.scrollAreaWidgetContents
        #self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 30, 261, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout()#self.gridLayoutWidget_2
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayoutWidget_2.setLayout(self.gridLayout)
        self.scrollArea.setWidget(self.gridLayoutWidget_2)
        self.attrsLayout.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.attrsLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add = QtWidgets.QPushButton(Dialog)
        self.add.setMaximumSize(QtCore.QSize(50, 23))
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add, 0, QtCore.Qt.AlignBottom)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setMaximumSize(QtCore.QSize(50, 23))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "属性编辑"))
        self.add.setText(_translate("Dialog", "确认"))
        self.cancel.setText(_translate("Dialog", "取消"))