# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteModelsUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(730, 631)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.groupBox_SelectSample = QtWidgets.QGroupBox(Dialog)
        self.groupBox_SelectSample.setObjectName("groupBox_SelectSample")
        self.horizontalLayout_openImage = QtWidgets.QHBoxLayout(self.groupBox_SelectSample)
        self.horizontalLayout_openImage.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_openImage.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_openImage.setSpacing(6)
        self.horizontalLayout_openImage.setObjectName("horizontalLayout_openImage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_SelectSample)
        self.label.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_Class = QtWidgets.QComboBox(self.groupBox_SelectSample)
        self.comboBox_Class.setEnabled(True)
        self.comboBox_Class.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_Class.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_Class.setEditable(False)
        self.comboBox_Class.setObjectName("comboBox_Class")
        self.horizontalLayout.addWidget(self.comboBox_Class)
        self.pushButton_Query = QtWidgets.QPushButton(self.groupBox_SelectSample)
        self.pushButton_Query.setMinimumSize(QtCore.QSize(71, 23))
        self.pushButton_Query.setMaximumSize(QtCore.QSize(71, 23))
        self.pushButton_Query.setObjectName("pushButton_Query")
        self.horizontalLayout.addWidget(self.pushButton_Query)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_SelectSample)
        self.checkBox.setMinimumSize(QtCore.QSize(15, 15))
        self.checkBox.setMaximumSize(QtCore.QSize(10, 10))
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.label_7 = QtWidgets.QLabel(self.groupBox_SelectSample)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tableView_List = QtWidgets.QTableView(self.groupBox_SelectSample)
        self.tableView_List.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableView_List.setStyleSheet("")
        self.tableView_List.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView_List.setObjectName("tableView_List")
        self.tableView_List.horizontalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableView_List)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_openImage.addLayout(self.verticalLayout_4)
        self.verticalLayoutMain.addWidget(self.groupBox_SelectSample)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.verticalLayout.addWidget(self.pushButton_accept, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutMain.addLayout(self.verticalLayout)
        self.horizontalLayout_1.addLayout(self.verticalLayoutMain)
        self.gridLayout_3.addLayout(self.horizontalLayout_1, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.pushButton_accept.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "删除模型"))
        self.groupBox_SelectSample.setTitle(_translate("Dialog", "模型选择："))
        self.label.setText(_translate("Dialog", "模型类别："))
        self.pushButton_Query.setText(_translate("Dialog", "查询"))
        self.checkBox.setToolTip(_translate("Dialog", "全选"))
        self.label_7.setText(_translate("Dialog", "模型列表："))
        self.pushButton_accept.setText(_translate("Dialog", "确定"))
