# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SamplesStatisticUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1007, 802)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_AttributeSelect = QtWidgets.QToolButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/VectorEditor_AttributeEdit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AttributeSelect.setIcon(icon)
        self.toolButton_AttributeSelect.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_AttributeSelect.setAutoRepeat(False)
        self.toolButton_AttributeSelect.setAutoExclusive(False)
        self.toolButton_AttributeSelect.setAutoRepeatDelay(300)
        self.toolButton_AttributeSelect.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_AttributeSelect.setAutoRaise(True)
        self.toolButton_AttributeSelect.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_AttributeSelect.setObjectName("toolButton_AttributeSelect")
        self.horizontalLayout.addWidget(self.toolButton_AttributeSelect)
        self.toolButton_ClearSelect = QtWidgets.QToolButton(Dialog)
        self.toolButton_ClearSelect.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/MarkTool_MarkClear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClearSelect.setIcon(icon1)
        self.toolButton_ClearSelect.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_ClearSelect.setAutoRaise(True)
        self.toolButton_ClearSelect.setObjectName("toolButton_ClearSelect")
        self.horizontalLayout.addWidget(self.toolButton_ClearSelect)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "样本库统计表"))
        self.toolButton_AttributeSelect.setToolTip(_translate("Dialog", "属性查询"))
        self.toolButton_AttributeSelect.setText(_translate("Dialog", "属性查询"))
        self.toolButton_ClearSelect.setToolTip(_translate("Dialog", "清除属性选择"))
        self.toolButton_ClearSelect.setText(_translate("Dialog", "..."))
import SamplesStatistic_rc
