# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SplitDatasetUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(736, 633)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_sampleClass = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_sampleClass.sizePolicy().hasHeightForWidth())
        self.comboBox_sampleClass.setSizePolicy(sizePolicy)
        self.comboBox_sampleClass.setObjectName("comboBox_sampleClass")
        self.horizontalLayout.addWidget(self.comboBox_sampleClass)
        self.pushButton_QuerySample = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_QuerySample.setObjectName("pushButton_QuerySample")
        self.horizontalLayout.addWidget(self.pushButton_QuerySample)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableView_sampleList = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_sampleList.setObjectName("tableView_sampleList")
        self.horizontalLayout_3.addWidget(self.tableView_sampleList)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_trainset = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_trainset.setEnabled(False)
        self.lineEdit_trainset.setObjectName("lineEdit_trainset")
        self.gridLayout.addWidget(self.lineEdit_trainset, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_valset = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_valset.setObjectName("lineEdit_valset")
        self.gridLayout.addWidget(self.lineEdit_valset, 0, 3, 1, 1)
        self.lineEdit_testset = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_testset.setObjectName("lineEdit_testset")
        self.gridLayout.addWidget(self.lineEdit_testset, 0, 5, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.pushButton_process = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_process.sizePolicy().hasHeightForWidth())
        self.pushButton_process.setSizePolicy(sizePolicy)
        self.pushButton_process.setObjectName("pushButton_process")
        self.verticalLayout.addWidget(self.pushButton_process, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        self.pushButton_process.clicked.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "数据集划分"))
        self.groupBox.setTitle(_translate("Dialog", "样本库选择："))
        self.label.setText(_translate("Dialog", "样本库查询："))
        self.pushButton_QuerySample.setText(_translate("Dialog", "查询"))
        self.groupBox_3.setTitle(_translate("Dialog", "样本库列表："))
        self.groupBox_2.setTitle(_translate("Dialog", "划分参数设置："))
        self.label_4.setText(_translate("Dialog", "测试集数量："))
        self.label_3.setText(_translate("Dialog", "验证集数量："))
        self.label_2.setText(_translate("Dialog", "训练集数量："))
        self.lineEdit_valset.setText(_translate("Dialog", "16"))
        self.lineEdit_testset.setText(_translate("Dialog", "0"))
        self.pushButton_process.setText(_translate("Dialog", "确定"))
