# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VectorLayerAttributeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton_AttributeSelect = QtWidgets.QToolButton(Dialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/AttributeQuery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_AttributeSelect.setIcon(icon)
        self.toolButton_AttributeSelect.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_AttributeSelect.setAutoRepeat(False)
        self.toolButton_AttributeSelect.setAutoExclusive(False)
        self.toolButton_AttributeSelect.setAutoRepeatDelay(300)
        self.toolButton_AttributeSelect.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_AttributeSelect.setAutoRaise(True)
        self.toolButton_AttributeSelect.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_AttributeSelect.setObjectName("toolButton_AttributeSelect")
        self.horizontalLayout.addWidget(self.toolButton_AttributeSelect)
        self.toolButton_ClearSelect = QtWidgets.QToolButton(Dialog)
        self.toolButton_ClearSelect.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/ClearSelection.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_ClearSelect.setIcon(icon1)
        self.toolButton_ClearSelect.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_ClearSelect.setAutoRaise(True)
        self.toolButton_ClearSelect.setObjectName("toolButton_ClearSelect")
        self.horizontalLayout.addWidget(self.toolButton_ClearSelect)
        self.toolButton_FieldCalculator = QtWidgets.QToolButton(Dialog)
        self.toolButton_FieldCalculator.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/FieldCalculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_FieldCalculator.setIcon(icon2)
        self.toolButton_FieldCalculator.setIconSize(QtCore.QSize(25, 25))
        self.toolButton_FieldCalculator.setAutoRaise(True)
        self.toolButton_FieldCalculator.setObjectName("toolButton_FieldCalculator")
        self.horizontalLayout.addWidget(self.toolButton_FieldCalculator)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 798, 531))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "属性表 - "))
        self.toolButton_AttributeSelect.setToolTip(_translate("Dialog", "属性选择"))
        self.toolButton_AttributeSelect.setText(_translate("Dialog", "属性选择"))
        self.toolButton_ClearSelect.setToolTip(_translate("Dialog", "清除选择"))
        self.toolButton_ClearSelect.setText(_translate("Dialog", "清除选择"))
        self.toolButton_FieldCalculator.setToolTip(_translate("Dialog", "字段计算器"))
        self.toolButton_FieldCalculator.setText(_translate("Dialog", "字段计算器"))
import SamplesStatistic_rc
